/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.knetikcloud.Api;
using com.knetikcloud.Model;
using com.knetikcloud.Client;
using System.Reflection;

namespace com.knetikcloud.Test
{
    /// <summary>
    ///  Class for testing Config
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfigTests
    {
        // TODO uncomment below to declare an instance variable for Config
        //private Config instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Config
            //instance = new Config();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Config
        /// </summary>
        [Test]
        public void ConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Config
            //Assert.IsInstanceOfType<Config> (instance, "variable 'instance' is a Config");
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PublicRead'
        /// </summary>
        [Test]
        public void PublicReadTest()
        {
            // TODO unit test for the property 'PublicRead'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
