/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.knetikcloud.Api;
using com.knetikcloud.Model;
using com.knetikcloud.Client;
using System.Reflection;

namespace com.knetikcloud.Test
{
    /// <summary>
    ///  Class for testing ConstantResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConstantResourceTests
    {
        // TODO uncomment below to declare an instance variable for ConstantResource
        //private ConstantResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConstantResource
            //instance = new ConstantResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConstantResource
        /// </summary>
        [Test]
        public void ConstantResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConstantResource
            //Assert.IsInstanceOfType<ConstantResource> (instance, "variable 'instance' is a ConstantResource");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'ValueType'
        /// </summary>
        [Test]
        public void ValueTypeTest()
        {
            // TODO unit test for the property 'ValueType'
        }

    }

}
