/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.knetikcloud.Api;
using com.knetikcloud.Model;
using com.knetikcloud.Client;
using System.Reflection;

namespace com.knetikcloud.Test
{
    /// <summary>
    ///  Class for testing SimpleGroupResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SimpleGroupResourceTests
    {
        // TODO uncomment below to declare an instance variable for SimpleGroupResource
        //private SimpleGroupResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SimpleGroupResource
            //instance = new SimpleGroupResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SimpleGroupResource
        /// </summary>
        [Test]
        public void SimpleGroupResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SimpleGroupResource
            //Assert.IsInstanceOfType<SimpleGroupResource> (instance, "variable 'instance' is a SimpleGroupResource");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UniqueName'
        /// </summary>
        [Test]
        public void UniqueNameTest()
        {
            // TODO unit test for the property 'UniqueName'
        }

    }

}
