/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.knetikcloud.Api;
using com.knetikcloud.Model;
using com.knetikcloud.Client;
using System.Reflection;

namespace com.knetikcloud.Test
{
    /// <summary>
    ///  Class for testing TimePeriodUsable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimePeriodUsableTests
    {
        // TODO uncomment below to declare an instance variable for TimePeriodUsable
        //private TimePeriodUsable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TimePeriodUsable
            //instance = new TimePeriodUsable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimePeriodUsable
        /// </summary>
        [Test]
        public void TimePeriodUsableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TimePeriodUsable
            //Assert.IsInstanceOfType<TimePeriodUsable> (instance, "variable 'instance' is a TimePeriodUsable");
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'TypeHint'
        /// </summary>
        [Test]
        public void TypeHintTest()
        {
            // TODO unit test for the property 'TypeHint'
        }
        /// <summary>
        /// Test the property 'MaxUse'
        /// </summary>
        [Test]
        public void MaxUseTest()
        {
            // TODO unit test for the property 'MaxUse'
        }
        /// <summary>
        /// Test the property 'TimeLength'
        /// </summary>
        [Test]
        public void TimeLengthTest()
        {
            // TODO unit test for the property 'TimeLength'
        }
        /// <summary>
        /// Test the property 'UnitOfTime'
        /// </summary>
        [Test]
        public void UnitOfTimeTest()
        {
            // TODO unit test for the property 'UnitOfTime'
        }

    }

}
