/* 
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.knetikcloud.Client.SwaggerDateConverter;

namespace com.knetikcloud.Model
{
    /// <summary>
    /// InventorySubscriptionResource
    /// </summary>
    [DataContract]
    public partial class InventorySubscriptionResource :  IEquatable<InventorySubscriptionResource>
    {
        /// <summary>
        /// The inventory status object
        /// </summary>
        /// <value>The inventory status object</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum InventoryStatusEnum
        {
            
            /// <summary>
            /// Enum Pending for "pending"
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending,
            
            /// <summary>
            /// Enum Active for "active"
            /// </summary>
            [EnumMember(Value = "active")]
            Active,
            
            /// <summary>
            /// Enum Inactive for "inactive"
            /// </summary>
            [EnumMember(Value = "inactive")]
            Inactive
        }

        /// <summary>
        /// The inventory status object
        /// </summary>
        /// <value>The inventory status object</value>
        [DataMember(Name="inventory_status", EmitDefaultValue=false)]
        public InventoryStatusEnum? InventoryStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InventorySubscriptionResource" /> class.
        /// </summary>
        /// <param name="BillDate">The date the subscription will be billed.</param>
        /// <param name="CreditLog">A record of past and present credit/debt changes.</param>
        /// <param name="GraceEnd">The date the grace period ends.</param>
        /// <param name="InventoryId">The id of the inventory.</param>
        /// <param name="InventoryStatus">The inventory status object.</param>
        /// <param name="ItemId">The id of the item.</param>
        /// <param name="PaymentMethod">The payment method object.</param>
        /// <param name="PriceOverride">The recurring price that has been set to override the base price. Null if not overriding.</param>
        /// <param name="PriceOverrideReason">An explanation for the reason the price is being overridden.</param>
        /// <param name="RecurringPrice">The default recurring price.</param>
        /// <param name="Sku">The recurring sku of the subscription.</param>
        /// <param name="StartDate">The date the subscription will start.</param>
        /// <param name="SubscriptionStatus">The status of the subscription.</param>
        /// <param name="User">The user.</param>
        public InventorySubscriptionResource(long? BillDate = default(long?), List<SubscriptionCreditResource> CreditLog = default(List<SubscriptionCreditResource>), long? GraceEnd = default(long?), int? InventoryId = default(int?), InventoryStatusEnum? InventoryStatus = default(InventoryStatusEnum?), int? ItemId = default(int?), PaymentMethodResource PaymentMethod = default(PaymentMethodResource), double? PriceOverride = default(double?), string PriceOverrideReason = default(string), double? RecurringPrice = default(double?), string Sku = default(string), long? StartDate = default(long?), int? SubscriptionStatus = default(int?), SimpleUserResource User = default(SimpleUserResource))
        {
            this.BillDate = BillDate;
            this.CreditLog = CreditLog;
            this.GraceEnd = GraceEnd;
            this.InventoryId = InventoryId;
            this.InventoryStatus = InventoryStatus;
            this.ItemId = ItemId;
            this.PaymentMethod = PaymentMethod;
            this.PriceOverride = PriceOverride;
            this.PriceOverrideReason = PriceOverrideReason;
            this.RecurringPrice = RecurringPrice;
            this.Sku = Sku;
            this.StartDate = StartDate;
            this.SubscriptionStatus = SubscriptionStatus;
            this.User = User;
        }
        
        /// <summary>
        /// The date the subscription will be billed
        /// </summary>
        /// <value>The date the subscription will be billed</value>
        [DataMember(Name="bill_date", EmitDefaultValue=false)]
        public long? BillDate { get; set; }

        /// <summary>
        /// A credit of money already applied to a subscription for the next bill, or a debt if negative
        /// </summary>
        /// <value>A credit of money already applied to a subscription for the next bill, or a debt if negative</value>
        [DataMember(Name="credit", EmitDefaultValue=false)]
        public double? Credit { get; private set; }

        /// <summary>
        /// A record of past and present credit/debt changes
        /// </summary>
        /// <value>A record of past and present credit/debt changes</value>
        [DataMember(Name="credit_log", EmitDefaultValue=false)]
        public List<SubscriptionCreditResource> CreditLog { get; set; }

        /// <summary>
        /// The date the grace period ends
        /// </summary>
        /// <value>The date the grace period ends</value>
        [DataMember(Name="grace_end", EmitDefaultValue=false)]
        public long? GraceEnd { get; set; }

        /// <summary>
        /// The id of the inventory
        /// </summary>
        /// <value>The id of the inventory</value>
        [DataMember(Name="inventory_id", EmitDefaultValue=false)]
        public int? InventoryId { get; set; }


        /// <summary>
        /// The id of the item
        /// </summary>
        /// <value>The id of the item</value>
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public int? ItemId { get; set; }

        /// <summary>
        /// The payment method object
        /// </summary>
        /// <value>The payment method object</value>
        [DataMember(Name="payment_method", EmitDefaultValue=false)]
        public PaymentMethodResource PaymentMethod { get; set; }

        /// <summary>
        /// The recurring price that has been set to override the base price. Null if not overriding
        /// </summary>
        /// <value>The recurring price that has been set to override the base price. Null if not overriding</value>
        [DataMember(Name="price_override", EmitDefaultValue=false)]
        public double? PriceOverride { get; set; }

        /// <summary>
        /// An explanation for the reason the price is being overridden
        /// </summary>
        /// <value>An explanation for the reason the price is being overridden</value>
        [DataMember(Name="price_override_reason", EmitDefaultValue=false)]
        public string PriceOverrideReason { get; set; }

        /// <summary>
        /// The default recurring price
        /// </summary>
        /// <value>The default recurring price</value>
        [DataMember(Name="recurring_price", EmitDefaultValue=false)]
        public double? RecurringPrice { get; set; }

        /// <summary>
        /// The recurring sku of the subscription
        /// </summary>
        /// <value>The recurring sku of the subscription</value>
        [DataMember(Name="sku", EmitDefaultValue=false)]
        public string Sku { get; set; }

        /// <summary>
        /// The date the subscription will start
        /// </summary>
        /// <value>The date the subscription will start</value>
        [DataMember(Name="start_date", EmitDefaultValue=false)]
        public long? StartDate { get; set; }

        /// <summary>
        /// The status of the subscription
        /// </summary>
        /// <value>The status of the subscription</value>
        [DataMember(Name="subscription_status", EmitDefaultValue=false)]
        public int? SubscriptionStatus { get; set; }

        /// <summary>
        /// The user
        /// </summary>
        /// <value>The user</value>
        [DataMember(Name="user", EmitDefaultValue=false)]
        public SimpleUserResource User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InventorySubscriptionResource {\n");
            sb.Append("  BillDate: ").Append(BillDate).Append("\n");
            sb.Append("  Credit: ").Append(Credit).Append("\n");
            sb.Append("  CreditLog: ").Append(CreditLog).Append("\n");
            sb.Append("  GraceEnd: ").Append(GraceEnd).Append("\n");
            sb.Append("  InventoryId: ").Append(InventoryId).Append("\n");
            sb.Append("  InventoryStatus: ").Append(InventoryStatus).Append("\n");
            sb.Append("  ItemId: ").Append(ItemId).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  PriceOverride: ").Append(PriceOverride).Append("\n");
            sb.Append("  PriceOverrideReason: ").Append(PriceOverrideReason).Append("\n");
            sb.Append("  RecurringPrice: ").Append(RecurringPrice).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  SubscriptionStatus: ").Append(SubscriptionStatus).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InventorySubscriptionResource);
        }

        /// <summary>
        /// Returns true if InventorySubscriptionResource instances are equal
        /// </summary>
        /// <param name="input">Instance of InventorySubscriptionResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InventorySubscriptionResource input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BillDate == input.BillDate ||
                    (this.BillDate != null &&
                    this.BillDate.Equals(input.BillDate))
                ) && 
                (
                    this.Credit == input.Credit ||
                    (this.Credit != null &&
                    this.Credit.Equals(input.Credit))
                ) && 
                (
                    this.CreditLog == input.CreditLog ||
                    (this.CreditLog != null &&
                    this.CreditLog.SequenceEqual(input.CreditLog))
                ) && 
                (
                    this.GraceEnd == input.GraceEnd ||
                    (this.GraceEnd != null &&
                    this.GraceEnd.Equals(input.GraceEnd))
                ) && 
                (
                    this.InventoryId == input.InventoryId ||
                    (this.InventoryId != null &&
                    this.InventoryId.Equals(input.InventoryId))
                ) && 
                (
                    this.InventoryStatus == input.InventoryStatus ||
                    (this.InventoryStatus != null &&
                    this.InventoryStatus.Equals(input.InventoryStatus))
                ) && 
                (
                    this.ItemId == input.ItemId ||
                    (this.ItemId != null &&
                    this.ItemId.Equals(input.ItemId))
                ) && 
                (
                    this.PaymentMethod == input.PaymentMethod ||
                    (this.PaymentMethod != null &&
                    this.PaymentMethod.Equals(input.PaymentMethod))
                ) && 
                (
                    this.PriceOverride == input.PriceOverride ||
                    (this.PriceOverride != null &&
                    this.PriceOverride.Equals(input.PriceOverride))
                ) && 
                (
                    this.PriceOverrideReason == input.PriceOverrideReason ||
                    (this.PriceOverrideReason != null &&
                    this.PriceOverrideReason.Equals(input.PriceOverrideReason))
                ) && 
                (
                    this.RecurringPrice == input.RecurringPrice ||
                    (this.RecurringPrice != null &&
                    this.RecurringPrice.Equals(input.RecurringPrice))
                ) && 
                (
                    this.Sku == input.Sku ||
                    (this.Sku != null &&
                    this.Sku.Equals(input.Sku))
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                ) && 
                (
                    this.SubscriptionStatus == input.SubscriptionStatus ||
                    (this.SubscriptionStatus != null &&
                    this.SubscriptionStatus.Equals(input.SubscriptionStatus))
                ) && 
                (
                    this.User == input.User ||
                    (this.User != null &&
                    this.User.Equals(input.User))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BillDate != null)
                    hashCode = hashCode * 59 + this.BillDate.GetHashCode();
                if (this.Credit != null)
                    hashCode = hashCode * 59 + this.Credit.GetHashCode();
                if (this.CreditLog != null)
                    hashCode = hashCode * 59 + this.CreditLog.GetHashCode();
                if (this.GraceEnd != null)
                    hashCode = hashCode * 59 + this.GraceEnd.GetHashCode();
                if (this.InventoryId != null)
                    hashCode = hashCode * 59 + this.InventoryId.GetHashCode();
                if (this.InventoryStatus != null)
                    hashCode = hashCode * 59 + this.InventoryStatus.GetHashCode();
                if (this.ItemId != null)
                    hashCode = hashCode * 59 + this.ItemId.GetHashCode();
                if (this.PaymentMethod != null)
                    hashCode = hashCode * 59 + this.PaymentMethod.GetHashCode();
                if (this.PriceOverride != null)
                    hashCode = hashCode * 59 + this.PriceOverride.GetHashCode();
                if (this.PriceOverrideReason != null)
                    hashCode = hashCode * 59 + this.PriceOverrideReason.GetHashCode();
                if (this.RecurringPrice != null)
                    hashCode = hashCode * 59 + this.RecurringPrice.GetHashCode();
                if (this.Sku != null)
                    hashCode = hashCode * 59 + this.Sku.GetHashCode();
                if (this.StartDate != null)
                    hashCode = hashCode * 59 + this.StartDate.GetHashCode();
                if (this.SubscriptionStatus != null)
                    hashCode = hashCode * 59 + this.SubscriptionStatus.GetHashCode();
                if (this.User != null)
                    hashCode = hashCode * 59 + this.User.GetHashCode();
                return hashCode;
            }
        }

    }

}
